# Generated by Django 5.0.4 on 2024-12-14 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('mbr_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100)),
                ('player_type', models.CharField(choices=[('hitter', 'Hitter'), ('pitcher', 'Pitcher')], max_length=10)),
                ('api_player_id', models.IntegerField(null=True, unique=True)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Hitter',
            fields=[
                ('player_id', models.OneToOneField(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='leaderboard.player')),
                ('average', models.FloatField(db_column='average', null=True)),
                ('ops', models.FloatField(db_column='ops', null=True)),
                ('plate_appearances', models.IntegerField(db_column='plate_appearances', null=True)),
                ('home_runs', models.IntegerField(db_column='home_runs', null=True)),
                ('rbis', models.IntegerField(db_column='rbis', null=True)),
                ('stolen_bases', models.IntegerField(db_column='stolen_bases', null=True)),
            ],
            options={
                'db_table': 'hitters',
            },
        ),
        migrations.CreateModel(
            name='Pitcher',
            fields=[
                ('player_id', models.OneToOneField(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='leaderboard.player')),
                ('wins', models.IntegerField(db_column='wins', null=True)),
                ('losses', models.IntegerField(db_column='losses', null=True)),
                ('era', models.FloatField(db_column='era', null=True)),
                ('strikeouts', models.IntegerField(db_column='strikeouts', null=True)),
            ],
            options={
                'db_table': 'pitchers',
            },
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(db_column='player_name', max_length=101)),
                ('is_alternate', models.BooleanField(blank=True, db_column='is_alternate', null=True)),
                ('pick_order', models.IntegerField(blank=True, db_column='pick_order', null=True)),
                ('pick_value', models.IntegerField(blank=True, db_column='pick_value', null=True)),
                ('category_id', models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboard.category')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboard.customuser')),
            ],
            options={
                'db_table': 'picks',
            },
        ),
    ]
